FIRST_NAME_FIELD = '//input[@id="firstname"]'
LAST_NAME_FIELD = '//input[@id="lastname"]'
EMAIL_FIELD = '//input[@id="email_address"]'
PASSWORD_FIELD = '//input[@id="password"]'
CONFIRM_PASSWORD_FIELD = '//input[@id="password-confirmation"]'
CREATE_BUTTON = '//button[@title="Create an Account"]'
ERROR_ALERT = '//div[@data-ui-id="message-error"]'
SUCCESS_AUTH_ALERT = '//div[@data-ui-id="message-success"]'
ERROR_FIELD_ALERT = '//div[@class="mage-error"]'
