FIRST_NAME = '//input[@id="firstName"]'
LAST_NAME = '//input[@id="lastName"]'
EMAIL = '//input[@id="userEmail"]'
RADIO_BUTTON = '//label[@for="gender-radio-1"]'
MOBILE_NUMBER = '//input[@id="userNumber"]'
DATE_PICKER = '//input[@id="dateOfBirthInput"]'
SUBJECTS_DROPDOWN = '//input[@id="subjectsInput"]'
CHECKBOX_1 = '//label[@for="hobbies-checkbox-1"]'
CHECKBOX_3 = '//label[@for="hobbies-checkbox-3"]'
CURRENT_ADDRESS = '//textarea[@id="currentAddress"]'
SUBMIT_BUTTON = '//button[@id="submit"]'
STATE_DROPDOWN = '//div[@id="state"]'
STATE_OPTION = '//div[@id="react-select-3-option-0"]'
CITY_DROPDOWN = '//div[@id="city"]'
CITY_OPTION = '//div[@id="react-select-4-option-0"]'
LABELS = '//tbody/tr/td[1]'
VALUES = '//tbody/tr/td[2]'

